steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/postergen-frontend', '.', '-f', 'webui/Dockerfile']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/postergen-frontend']

  # Deploy the container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'postergen-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/postergen-frontend'
      - '--region'
      - 'us-east4' # Replace with your GCP region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/postergen-frontend'
